require.config({baseUrl:"/js",paths:{jquery:"libs/jquery/jquery-min",underscore:"libs/underscore/underscore",backbone:"libs/backbone/backbone",text:"libs/require/text",less:"libs/less",iscroll:"libs/iscroll",base64:"libs/base64",mustache:"libs/mustache/mustache"}});window.storage=chrome.storage.local;window.getMessage=chrome.i18n.getMessage;var extensionVersion="0.1.0";
"undefined"!==typeof chrome.runtime&&chrome.runtime.onInstalled.addListener(function(d){console.log("extension install/updated. details: ",d);storage.set({isNewInstall:d.reason})});
require("jquery,underscore,collections/task,collections/category,helpers/getFetchOptions,server/auth,server/sync,chrome/helpers,helpers/alert,constants,config/user,base64".split(","),function(d,w,x,y,f,k,D,z,l,E,A,B){function r(){c&&l.checkReminders()}function C(){storage.get("userPuid",function(a){a=a.puid;if(a!=null){storage.remove("password");m("AnyDO-Puid",a);s()}else d.ajax({url:ME_URL,type:"get",xhrFields:{withCredentials:true},crossDomain:true,success:function(a){storage.set({userPuid:a.id});
m("AnyDO-Puid",a.id);s()}})}.bind(this))}function h(){return((1+Math.random())*65536|0).toString(16).substring(1)}function m(a,b){d(document).on("ajaxSend",function(d,c){c.setRequestHeader(a,b)})}function t(){var a=["0"];a[1]=i.getCalendarDay().toString();a[2]=i.getView()==VIEW_BY_DUE_DATE?"0":i.getView()==VIEW_BY_CATEGORY?"1":i.getView()==VIEW_BY_PRIORITY?"2":"#";console.log("bitFlag",a.join(""));return a.join("")}function s(){storage.get(["isNewInstall","userPuid","userName"],function(a){if(a.isNewInstall!=
null){console.log("reporting installation for user");d.ajax({url:ME_URL,type:"put",contentType:"application/json",data:JSON.stringify({id:a.userPuid,name:a.userName,instDetails:{installationId:btoa((h()+h()+"-"+h()+"-"+h()).slice(2)),version_code:extensionVersion,platform:"WEB",userSettings:t()}}),crossDomain:true});if(a.isNewInstall=="install"){a=new Date;a=""+a.getUTCFullYear()+(a.getUTCMonth()+1)+a.getUTCDate();_gaq.push(["_setCustomVar",5,"Installed",a,1])}storage.remove("isNewInstall")}})}function j(){_gaq.push(["_setCustomVar",
2,"Settings Flags",t(),1]);if(c)console.log("Initialization already done.");else{console.log("Background page: logging in.");C();tasks=new x;categories=new y;tasks.bind("reset",function(){c=true;l.updateReminders(categories,tasks,void 0)});categories.fetch(f("categories"));tasks.fetch(f("tasks"))}}function e(){console.log("%c POLLING "+new Date,"background: yellow; font-size: 20px;");if(c){n=2;u()}}function o(a){var b=new d.Deferred;if(a==="categories"){console.log("trying to sync categories now");
categories.fetch(f("categories",b))}if(a==="tasks"){console.log("trying to sync tasks now");tasks.fetch(f("tasks",b))}if(a==="notes"){console.log("trying to sync notes now");tasks.fetch(f("tasks",b))}return b.promise()}function u(){if(n>0){console.log("%c ------------------------------------ SYNCING ----------------------------","background: cyan; font-weight: bold;");o("categories").done(function(){o("tasks").done(function(){o("notes")})}).fail(function(){n--;console.log("%c ------------------------------------ RETRYING ----------------------------",
"background: orange; font-weight: bold;");setTimeout(u,1500)})}}function g(){typeof popup=="object"&&messagePopup({action:"refreshTab"})}function v(a){if(typeof popup!=="undefined"){popup.focus();typeof a=="function"&&a()}else chrome.app.window.create("index.html",{width:270,height:600,minWidth:270,minHeight:300,maxWidth:650,type:"shell"},function(b){window.popup=b;typeof a=="function"&&a();b.onClosed.addListener(function(){window.popup=void 0;trackPageview("/closePopup")})})}var c=false;window.userValues=
{};storage.get(null,function(a){userValues=a});chrome.storage.onChanged.addListener(function(a){w.each(a,function(a,c){userValues[c]=a.newValue});if(a.tasks){console.log("Tasks changed from another page");c=true}});window._gaq=window._gaq||[];_gaq.push(["_setAccount",SERVER_API_URL.indexOf("sm-prod")>-1?"UA-28645084-6":"UA-28645272-1"]);_gaq.push(["_setCustomVar",1,"Chrome Packaged App Version Code",extensionVersion,1]);m("AnyDO-Version",extensionVersion);window.tasks=void 0;window.categories=void 0;
var p=null,i=new A,n=2;window.createGlobalId=function(){for(var a="",b=0;b<16;b++)a=a+String.fromCharCode(Math.random()*256);return B.encodeBase64(a).replace(/\//g,"_").replace(/\+/g,"-")};window.trackPageview=function(a){_gaq.push(["_trackPageview",a])};window.track=function(a){a=d.map(a,function(a){return a});switch(a.length){case 0:case 1:console.error("Google Analytics: You should use at least a Category and an Action");break;case 2:_gaq.push(["_trackEvent",a[0],a[1]]);break;case 3:_gaq.push(["_trackEvent",
a[0],a[1],a[2]]);break;case 4:_gaq.push(["_trackEvent",a[0],a[1],a[2],a[3]])}};chrome.runtime.onMessage.addListener(function(a,b,d){console.log("Got runtime.onMessage",a);switch(a.action){case "facebookConnectComplete":k.logInWithFacebook(a.access_token,function(){window.storage.setItem("access_token",a.access_token);j();OPEN_POPUP&&popupWindow();chrome.extension.sendRequest({action:"facebookConnectComplete",success:true})},function(){alert("There was an error logging in with Facebook. Please try again.");
window.storage.removeItem("access_token");chrome.tabs.getSelected(null,function(a){chrome.tabs.sendRequest(a.id,{action:"facebookConnectComplete",success:false})})});break;case "logIn":j();break;case "logOut":c=false;console.log("Background page: logging out.");break;case "refresh":c&&l.updateReminders(categories,tasks,a.task);break;case "pollServer":e();break;case "report":console.log("reporting to GA",a.report);_gaq.push(a.report);break;case "track":track(a.track);break;case "trackPageview":trackPageview(a.track);
break;case "openPage":console.log("Opening external page "+a.url);chrome.tabs.create({url:a.url});break;case "updateHiddenStatus":console.log("tab",b.tab.id,"tabsHidden[sender.tab.id]",a.hidden);break;case "popupWindow":popupWindow();break;case "closePopup":if(p){chrome.windows.remove(p.id);p=null}}d()});window.addEventListener("message",function(a){console.log("Got 'message' event",a.data);var b=a.data;switch(b.type){case "report":_gaq.push.apply(_gaq,b.report);break;case "alert":switch(b.alert){case "done":if(tasks)if(tasks.get(b.id)){tasks.get(b.id).markAsChecked();
g()}else console.error("can't find task ID!");else console.error("Can't find the tasks collection!");break;case "snooze":if(tasks){tasks.get(b.id).snoozeTask(6E4*b.minutes);g()}else console.error("Can't find the tasks collection!");break;case "dismiss":tasks.get(b.id).dismissAlert(g);g()}break;case "highlightTask":v(function(){console.log("Ha popup opened",b.highlightedTask)});break;case "log":console.log(b.log);break;case "refreshTab":g();break;case "isLoggedIn":console.log("is LOGGEDI N?!!!",c,
arguments);break;case "pollServer":e();break;case "startPollingServer":q=setInterval(e,18E5);e();break;case "stopPollingServer":clearInterval(q)}});var q=void 0;chrome.app.runtime.onLaunched.addListener(v);window.messagePopup=function(a){typeof popup=="object"&&typeof popup.contentWindow!=="undefined"&&popup.contentWindow.postMessage(a,"*")};window.messageBackgroundPage=function(a){chrome.runtime.getBackgroundPage(function(b){b.postMessage(a,"*")})};window.onerror=function(a,b,c){_gaq.push(["_trackEvent",
"Exceptions","Application","["+b+" ("+c+")] "+a,null,true])};console.log("Setting up timers...");j();setInterval(r,1E4);r();q=setInterval(e,18E5);e();z.initializeAlerts();console.log("Background page initialized successfully.");k.isCredentialsSaved(function(){k.logInUsingStoredCredentials(function(){j()},function(){console.log("Can't log in for some reason.")})})});